runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://dispatch_user:yXDnjmPGCoew2W3RtBib@localhost/dispatch?host=/cloudsql/care-and-cure-dispatch:us-central1:dispatch-db"
  JWT_SECRET: "x1RgkTWDmCqrGLYob7QhZ48w6cjKOXBe"
  JWT_EXPIRES_IN: "7d"
  TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_WHATSAPP_NUMBER: "whatsapp:+14155238886"
  CLOUDINARY_CLOUD_NAME: "your-cloud-name"
  CLOUDINARY_API_KEY: "your-api-key"
  CLOUDINARY_API_SECRET: "your-api-secret"
  CORS_ORIGIN: "*"

handlers:
  # Dynamic routes (API + health + websocket)
  - url: /api/.*
    script: auto
    secure: always

  - url: /socket.io/.*
    script: auto
    secure: always

  - url: /health
    script: auto
    secure: always

  # Static assets built by Vite
  - url: /assets/(.*)
    static_files: client/dist/assets/\1
    upload: client/dist/assets/(.*)
    secure: always
    expiration: "0s"
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
      Pragma: "no-cache"
      Expires: "0"

  # SPA fallback: serve index.html for all other routes
  - url: /.*
    static_files: client/dist/index.html
    upload: client/dist/index.html
    secure: always
    expiration: "0s"
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
      Pragma: "no-cache"
      Expires: "0"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
