runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"

handlers:
  # Serve static files from client/dist
  - url: /assets
    static_dir: client/dist/assets
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
