runtime: nodejs20

instance_class: F2

# Cloud SQL Connection
vpc_access_connector:
  name: "projects/care-and-cure-dispatch/locations/us-central1/connectors/dispatch-connector"

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://dispatch_user:yXDnjmPGCoew2W3RtBib@/dispatch?host=/cloudsql/care-and-cure-dispatch:us-central1:dispatch-db"
  JWT_SECRET: "x1RgkTWDmCqrGLYob7QhZ48w6cjKOXBe"
  JWT_EXPIRES_IN: "7d"
  TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
  TWILIO_AUTH_TOKEN: "your-twilio-auth-token"
  TWILIO_WHATSAPP_NUMBER: "whatsapp:+14155238886"
  CLOUDINARY_CLOUD_NAME: "your-cloud-name"
  CLOUDINARY_API_KEY: "your-api-key"
  CLOUDINARY_API_SECRET: "your-api-secret"
  CORS_ORIGIN: "*"

handlers:
  # Serve static files from client/dist
  - url: /assets
    static_dir: client/dist/assets
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
