steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:$SHORT_SHA'
      - '-t'
      - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:latest'
      - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cure-care-dispatch'
      - '--image'
      - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:$SHORT_SHA'
  - 'gcr.io/care-and-cure-dispatch/cure-care-dispatch:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
